# Generated by Django 4.2.16 on 2026-04-10 22:23

import apps.ressources.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_ressource', models.CharField(choices=[('cours', 'Cours'), ('sujet', "Sujet d'examen"), ('td', 'Travaux dirigés'), ('tp', 'Travaux pratiques'), ('autre', 'Autre')], default='cours', max_length=20)),
                ('fichier', models.FileField(upload_to=apps.ressources.models.upload_to)),
                ('annee', models.PositiveSmallIntegerField(blank=True, help_text='Année académique', null=True)),
                ('description', models.TextField(blank=True)),
                ('nb_telechargements', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='catalogue.matiere')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
